[package]
name = "axum-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "^0.8.4"
tokio = { version = "^1", features = ["full"] }
serde = { version = "^1", features = ["derive"] }
tower = "0.5.2"
tower-http = "0.6.6"
